window.SAWADIKA_CATEGORIES = [
  "Entree",
  "Thai Food",
  "Indian Food",
  "Jap Food",
  "Sushi & Rolls",
  "Box",
  "Dessert",
  "Boissons"
];

window.SAWADIKA_MENU = [
  { id: "ent-1", category: "Entree", name: "Nems poulet x4", desc: "Nems de poulet croustillants.", price: 4.50 },
  { id: "ent-2", category: "Entree", name: "Nems crevette x4", desc: "Nems aux crevettes croustillants.", price: 5.50 },
  { id: "ent-3", category: "Entree", name: "Gyozas legumes x4", desc: "Raviolis japonais aux legumes.", price: 4.50 },
  { id: "ent-4", category: "Entree", name: "Tempura poulet x6", desc: "Beignets de poulet legers et croustillants.", price: 4.50 },
  { id: "ent-5", category: "Entree", name: "Tempura crevette x3", desc: "Crevettes en tempura.", price: 5.50 },
  { id: "ent-6", category: "Entree", name: "Yakitori poulet x2", desc: "Brochettes de poulet grillees.", price: 5.50 },
  { id: "ent-7", category: "Entree", name: "Yakitori boeuf fromage x2", desc: "Brochettes boeuf fromage.", price: 5.50 },
  { id: "ent-8", category: "Entree", name: "Yakitori saumon x2", desc: "Brochettes de saumon grillees.", price: 6.00 },
  { id: "ent-9", category: "Entree", name: "Edamame", desc: "Feveroles de soja salees.", price: 3.90 },
  { id: "ent-10", category: "Entree", name: "Edamame spicy", desc: "Edamame releves.", price: 4.00 },
  { id: "ent-11", category: "Entree", name: "Riz nature", desc: "Bol de riz blanc.", price: 2.50 },
  { id: "ent-12", category: "Entree", name: "Riz vinaigre", desc: "Bol de riz vinaigre.", price: 3.00 },
  { id: "ent-13", category: "Entree", name: "Soupe miso", desc: "Soupe miso classique.", price: 3.00 },
  { id: "ent-14", category: "Entree", name: "Soupe miso spicy", desc: "Soupe miso relevee.", price: 3.90 },
  { id: "tha-1", category: "Thai Food", name: "Pad Thai", desc: "Nouilles de riz sautees aux legumes, poulet katsu ou crevette.", price: 11.50 },
  { id: "tha-2", category: "Thai Food", name: "Khao Phat", desc: "Riz thai saute aux legumes, boeuf ou poulet katsu.", price: 11.90 },
  { id: "tha-3", category: "Thai Food", name: "Tigre qui pleure", desc: "Bavette marinee, riz thai saute aux legumes, sauce piquante.", price: 13.90 },
  { id: "tha-4", category: "Thai Food", name: "Lampang", desc: "Riz cantonais, tempura de poulet ou crevette, sauce piquante.", price: 12.50 },
  { id: "tha-5", category: "Thai Food", name: "Chicken Satay", desc: "Nouilles de riz sautees aux legumes, poulet, sauce satay.", price: 12.50 },
  { id: "ind-1", category: "Indian Food", name: "Chicken Curry", desc: "Riz blanc, poulet aux epices indiennes, sauce curry.", price: 8.90 },
  { id: "ind-2", category: "Indian Food", name: "Butter Chicken/Korma", desc: "Riz blanc, poulet, creme, sauce tomate, noix de cajou.", price: 9.90 },
  { id: "ind-3", category: "Indian Food", name: "Crevettes Masala", desc: "Riz, crevettes decortiquees, sauce curry.", price: 12.50 },
  { id: "ind-4", category: "Indian Food", name: "Fish Curry", desc: "Riz, filet de saumon au curry traditionnel.", price: 12.50 },
  { id: "ind-5", category: "Indian Food", name: "Egg Rice", desc: "Riz, legumes, oeufs et epices.", price: 7.50 },
  { id: "ind-6", category: "Indian Food", name: "Special Pulao Rice", desc: "Riz parfume, epices indiennes.", price: 8.50 },
  { id: "jap-yaki-poulet", category: "Jap Food", subgroup: "Yakisoba", groupDesc: "Nouilles sautees, legumes, sauce japonaise.", name: "Poulet", desc: "Yakisoba", price: 10.50 },
  { id: "jap-yaki-boeuf", category: "Jap Food", subgroup: "Yakisoba", groupDesc: "Nouilles sautees, legumes, sauce japonaise.", name: "Boeuf", desc: "Yakisoba", price: 10.90 },
  { id: "jap-yaki-saumon", category: "Jap Food", subgroup: "Yakisoba", groupDesc: "Nouilles sautees, legumes, sauce japonaise.", name: "Saumon", desc: "Yakisoba", price: 11.50 },
  { id: "jap-yaki-crevette", category: "Jap Food", subgroup: "Yakisoba", groupDesc: "Nouilles sautees, legumes, sauce japonaise.", name: "Crevette", desc: "Yakisoba", price: 10.90 },
  { id: "jap-yaki-veggie", category: "Jap Food", subgroup: "Yakisoba", groupDesc: "Nouilles sautees, legumes, sauce japonaise.", name: "Veggie", desc: "Yakisoba", price: 9.90 },
  { id: "jap-ramen-poulet", category: "Jap Food", subgroup: "Ramen", groupDesc: "Nouilles, legumes, oeuf, bouillon japonais.", name: "Poulet", desc: "Ramen", price: 12.00 },
  { id: "jap-ramen-boeuf", category: "Jap Food", subgroup: "Ramen", groupDesc: "Nouilles, legumes, oeuf, bouillon japonais.", name: "Boeuf", desc: "Ramen", price: 12.50 },
  { id: "jap-ramen-saumon", category: "Jap Food", subgroup: "Ramen", groupDesc: "Nouilles, legumes, oeuf, bouillon japonais.", name: "Saumon", desc: "Ramen", price: 12.50 },
  { id: "jap-ramen-crevette", category: "Jap Food", subgroup: "Ramen", groupDesc: "Nouilles, legumes, oeuf, bouillon japonais.", name: "Crevette", desc: "Ramen", price: 12.50 },
  { id: "jap-ramen-veggie", category: "Jap Food", subgroup: "Ramen", groupDesc: "Nouilles, legumes, oeuf, bouillon japonais.", name: "Veggie", desc: "Ramen", price: 10.90 },
  { id: "jap-poke-poulet", category: "Jap Food", subgroup: "Poke Bowl", groupDesc: "Riz vinaigre, legumes.", name: "Poulet", desc: "Poke Bowl", price: 12.50 },
  { id: "jap-poke-thon", category: "Jap Food", subgroup: "Poke Bowl", groupDesc: "Riz vinaigre, legumes.", name: "Thon", desc: "Poke Bowl", price: 13.90 },
  { id: "jap-poke-saumon", category: "Jap Food", subgroup: "Poke Bowl", groupDesc: "Riz vinaigre, legumes.", name: "Saumon", desc: "Poke Bowl", price: 12.90 },
  { id: "jap-poke-crevette", category: "Jap Food", subgroup: "Poke Bowl", groupDesc: "Riz vinaigre, legumes.", name: "Crevette", desc: "Poke Bowl", price: 12.50 },
  { id: "jap-poke-veggie", category: "Jap Food", subgroup: "Poke Bowl", groupDesc: "Riz vinaigre, legumes.", name: "Veggie", desc: "Poke Bowl", price: 11.90 },
  { id: "jap-chirashi-saumon", category: "Jap Food", subgroup: "Chirashi", groupDesc: "Riz vinaigre.", name: "Saumon", desc: "Riz vinaigre, saumon.", price: 11.50 },
  { id: "jap-chirashi-saumon-tataki", category: "Jap Food", subgroup: "Chirashi", groupDesc: "Riz vinaigre.", name: "Saumon Tataki", desc: "Riz vinaigre, saumon snacke, guacamole yuzu, sauce ponzu.", price: 11.90 },
  { id: "jap-chirashi-thon", category: "Jap Food", subgroup: "Chirashi", groupDesc: "Riz vinaigre.", name: "Thon", desc: "Riz vinaigre, thon.", price: 13.90 },
  { id: "sr-signature-tigre", category: "Sushi & Rolls", subgroup: "Signature x8", groupDesc: "", name: "Tigre", desc: "Signature x8", price: 9.90 },
  { id: "sr-signature-dragon", category: "Sushi & Rolls", subgroup: "Signature x8", groupDesc: "", name: "Dragon Roll", desc: "Signature x8", price: 9.90 },
  { id: "sr-signature-red-dragon", category: "Sushi & Rolls", subgroup: "Signature x8", groupDesc: "", name: "Red Dragon", desc: "Signature x8", price: 9.90 },
  { id: "sr-signature-avocado", category: "Sushi & Rolls", subgroup: "Signature x8", groupDesc: "", name: "Avocado", desc: "Signature x8", price: 8.50 },
  { id: "sr-salmon-cheese", category: "Sushi & Rolls", subgroup: "Salmon x8", groupDesc: "", name: "Cheese", desc: "Salmon x8", price: 7.50 },
  { id: "sr-salmon-avocat", category: "Sushi & Rolls", subgroup: "Salmon x8", groupDesc: "", name: "Avocat", desc: "Salmon x8", price: 7.80 },
  { id: "sr-salmon-avocat-cheese", category: "Sushi & Rolls", subgroup: "Salmon x8", groupDesc: "", name: "Avocat, Cheese", desc: "Salmon x8", price: 7.90 },
  { id: "sr-crispy-poulet-cheese", category: "Sushi & Rolls", subgroup: "Crispy x8", groupDesc: "", name: "Poulet, Cheese", desc: "Crispy x8", price: 6.50 },
  { id: "sr-crispy-poulet-avocat", category: "Sushi & Rolls", subgroup: "Crispy x8", groupDesc: "", name: "Poulet, Avocat", desc: "Crispy x8", price: 6.90 },
  { id: "sr-crispy-saumon-cheese", category: "Sushi & Rolls", subgroup: "Crispy x8", groupDesc: "", name: "Saumon, Cheese", desc: "Crispy x8", price: 6.90 },
  { id: "sr-crispy-tempura-crevette", category: "Sushi & Rolls", subgroup: "Crispy x8", groupDesc: "", name: "Tempura crevette", desc: "Crispy x8", price: 6.80 },
  { id: "sr-crispy-tempura-mangue", category: "Sushi & Rolls", subgroup: "Crispy x8", groupDesc: "", name: "Tempura mangue", desc: "Crispy x8", price: 6.90 },
  { id: "sr-california-saumon-avocat", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Saumon, avocat", desc: "California x8", price: 6.10 },
  { id: "sr-california-saumon-cheese", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Saumon, cheese", desc: "California x8", price: 6.00 },
  { id: "sr-california-saumon-concombre-spicy", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Saumon, concombre, spicy", desc: "California x8", price: 6.50 },
  { id: "sr-california-thon-avocat", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Thon, avocat", desc: "California x8", price: 6.20 },
  { id: "sr-california-thon-cut-avocat", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Thon cut, avocat", desc: "California x8", price: 6.20 },
  { id: "sr-california-avocat-concombre-cheese", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Avocat, concombre, cheese", desc: "California x8", price: 6.00 },
  { id: "sr-california-poulet-cheese", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Poulet, cheese", desc: "California x8", price: 6.90 },
  { id: "sr-california-avocat-cheese", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Avocat, cheese", desc: "California x8", price: 6.50 },
  { id: "sr-california-tempura-crevette", category: "Sushi & Rolls", subgroup: "California x8", groupDesc: "", name: "Tempura, crevette", desc: "California x8", price: 5.90 },
  { id: "sr-green-saumon-avocat", category: "Sushi & Rolls", subgroup: "Green x8", groupDesc: "", name: "Saumon, avocat", desc: "Green x8", price: 6.00 },
  { id: "sr-green-saumon-menthe-cheese", category: "Sushi & Rolls", subgroup: "Green x8", groupDesc: "", name: "Saumon, menthe, cheese", desc: "Green x8", price: 6.00 },
  { id: "sr-green-avocat-cheese", category: "Sushi & Rolls", subgroup: "Green x8", groupDesc: "", name: "Avocat, cheese", desc: "Green x8", price: 6.50 },
  { id: "sr-green-crevette-menthe", category: "Sushi & Rolls", subgroup: "Green x8", groupDesc: "", name: "Crevette, menthe", desc: "Green x8", price: 6.90 },
  { id: "sr-green-thon-cut-avocat", category: "Sushi & Rolls", subgroup: "Green x8", groupDesc: "", name: "Thon cut, avocat", desc: "Green x8", price: 6.50 },
  { id: "sr-maki-saumon", category: "Sushi & Rolls", subgroup: "Maki x6", groupDesc: "", name: "Saumon", desc: "Maki x6", price: 5.00 },
  { id: "sr-maki-avocat-cheese", category: "Sushi & Rolls", subgroup: "Maki x6", groupDesc: "", name: "Avocat, cheese", desc: "Maki x6", price: 4.90 },
  { id: "sr-maki-saumon-concombre", category: "Sushi & Rolls", subgroup: "Maki x6", groupDesc: "", name: "Saumon, concombre", desc: "Maki x6", price: 5.50 },
  { id: "sr-maki-avocat", category: "Sushi & Rolls", subgroup: "Maki x6", groupDesc: "", name: "Avocat", desc: "Maki x6", price: 4.50 },
  { id: "sr-maki-thon", category: "Sushi & Rolls", subgroup: "Maki x6", groupDesc: "", name: "Thon", desc: "Maki x6", price: 5.70 },
  { id: "sr-sashimi-6-saumon", category: "Sushi & Rolls", subgroup: "Sashimi", groupDesc: "", name: "6 tranches de saumon", desc: "Sashimi", price: 6.90 },
  { id: "sr-sashimi-10-saumon", category: "Sushi & Rolls", subgroup: "Sashimi", groupDesc: "", name: "10 tranches de saumon", desc: "Sashimi", price: 10.90 },
  { id: "sr-sashimi-6-thon", category: "Sushi & Rolls", subgroup: "Sashimi", groupDesc: "", name: "6 tranches de thon", desc: "Sashimi", price: 7.90 },
  { id: "sr-sashimi-10-thon", category: "Sushi & Rolls", subgroup: "Sashimi", groupDesc: "", name: "10 tranches de thon", desc: "Sashimi", price: 11.90 },
  { id: "sr-sashimi-assortiment", category: "Sushi & Rolls", subgroup: "Sashimi", groupDesc: "", name: "Assortiment : 8 saumon & 7 thon", desc: "Sashimi", price: 13.90 },
  { id: "sr-nigiri-2-saumon", category: "Sushi & Rolls", subgroup: "Nigiris", groupDesc: "", name: "2 saumon", desc: "Nigiris", price: 4.00 },
  { id: "sr-nigiri-2-thon", category: "Sushi & Rolls", subgroup: "Nigiris", groupDesc: "", name: "2 thon", desc: "Nigiris", price: 4.50 },
  { id: "sr-nigiri-2-saumon-snacke", category: "Sushi & Rolls", subgroup: "Nigiris", groupDesc: "", name: "2 saumon snacke", desc: "Nigiris", price: 4.50 },
  { id: "sr-nigiri-2-saumon-cheese", category: "Sushi & Rolls", subgroup: "Nigiris", groupDesc: "", name: "2 saumon cheese", desc: "Nigiris", price: 4.20 },
  { id: "box-saumon-x20", category: "Box", name: "Saumon x20", desc: "Box saumon.", price: 15.90, composition: ["California saumon, avocat x8", "Green saumon, menthe, cheese x8", "Nigiris saumon x4"] },
  { id: "box-mixte-x20", category: "Box", name: "Mixte x20", desc: "Box mixte.", price: 16.90, composition: ["California saumon, avocat x8", "Maki thon x6", "Nigiris saumon x2", "Nigiris thon x2", "Nigiris crevette x2"] },
  { id: "box-california-x24", category: "Box", name: "California x24", desc: "Box california.", price: 16.90, composition: ["California saumon avocat x8", "California tempura crevette x8", "California poulet cheese x8"] },
  { id: "box-veggie-x24", category: "Box", name: "Veggie x24", desc: "Box veggie.", price: 14.90, composition: ["California avocat, cheese x8", "Green veggie, miel x8", "California avocat, concombre, carotte x8"] },
  { id: "box-classique-x44", category: "Box", name: "Classique x44", desc: "Grande box classique.", price: 40.90, composition: ["California saumon, avocat x8", "California poulet crispy x8", "Green saumon, menthe, cheese x8", "Red dragon x8", "Salmon roll cheese x6", "Nigiris saumon x2", "Nigiris thon x2", "Nigiris crevette x2"] },
  { id: "box-premium-x54", category: "Box", name: "Premium x54", desc: "Grande box premium.", price: 49.90, composition: ["California saumon, avocat x8", "Green saumon, cheese x8", "Crispy roll poulet, cheese x8", "Dragon roll x8", "Salmon roll cheese x8", "California avocat, cheese x8", "Nigiris saumon x2", "Nigiris saumon teriyaki x2", "Nigiris thon snacke x2"] },
  { id: "des-1", category: "Dessert", name: "Mango Sticky Rice", desc: "Riz gluant au lait de coco et mangue.", price: 4.90 },
  { id: "des-2", category: "Dessert", name: "Mangue fraiche", desc: "Portion de mangue fraiche.", price: 4.00 },
  { id: "des-3", category: "Dessert", name: "Mochi glace", desc: "Mochi glace.", price: 4.90 },
  { id: "des-4", category: "Dessert", name: "Tiramisu", desc: "Tiramisu maison.", price: 4.00 },
  { id: "des-5", category: "Dessert", name: "Fondant au chocolat", desc: "Fondant au chocolat.", price: 4.00 },
  { id: "boi-1", category: "Boissons", name: "Soda 33cl", desc: "Canette 33cl.", price: 1.90 },
  { id: "boi-2", category: "Boissons", name: "Ramune 20cl", desc: "Boisson japonaise.", price: 3.50 },
  { id: "boi-3", category: "Boissons", name: "Mangajo 25cl", desc: "Boisson the infusion.", price: 3.50 },
  { id: "boi-4", category: "Boissons", name: "Eau 50cl", desc: "Bouteille d eau 50cl.", price: 1.00 }
];

window.SAWADIKA_EMAIL = "sawadika689@gmail.com";
window.SAWADIKA_CART_KEY = "sawadika_cart";

window.priceEUR = function priceEUR(value) {
  return Number(value).toFixed(2).replace('.', ',') + " EUR";
};
